#!/bin/bash

printf -- "-------------------Script Auto Restart UDPGW-------------------\n"
sleep 0.5
printf -- "--------Memeriksa dan Mematikan UDPGW yg masih berjalan--------\n"
sleep 0.5
killall badvpn-udpgw
printf ">>>>>>>>>>>>>>>>>>>>>UDPGW Telah Dimatikan<<<<<<<<<<<<<<<<<<<<<\n\n"
sleep 0.5
printf -- "-------------------Memeriksa Duplikat UDPGW-------------------\n"
sleep 0.5
if [ -f /usr/bin/badvpn-udpgw ] && [ -f /usr/local/bin/badvpn-udpgw ]
then
printf -- "-----Terdapat Duplikat UDPGW dari Repo Github dan Auto Installer-----\n>>>>>>>>>>>>>Menggunakan UDPGW dari Auto Installer<<<<<<<<<<<<<\n\n" && wget https://raw.githubusercontent.com/ikhsan-rfl/vps-reseller-tools/master/udpgw-res/useauto -O useauto && chmod +x useauto && ./useauto && rm useauto
sleep 0.5
else
sleep 0.5
printf -- ">>>>>>>>>>>>>>>>>>>>Tidak Terdapat Duplikat UDPGW<<<<<<<<<<<<<<<<<<\n\n" && wget https://raw.githubusercontent.com/ikhsan-rfl/vps-reseller-tools/master/udpgw-res/check -O check && chmod +x check && ./check && rm check
fi


